### PR TITLE
(AdoptOpenJDK) Wording and switch cleanup

### PR DESCRIPTION
**Pull request by RedBaron2**
@johanjanssen @johanjanssen-sanoma 
The following are changes that need to be made to the wording of the readme. The changes to the switches to work correctly all the time.

I have looked into an issue related to #7 and filed it [here](https://github.com/AdoptOpenJDK/openjdk-installer/issues/223)
This issue makes the example even on AdoptOpenJDK website not work correctly. I feel that due to this issue a preferred method of using the `INSTALLLEVEL` is recommended.

Thanks for looking into this PR.

### CODE REVIEW

**Comment by johanjanssen** [comment]
Wanted to merge this one, but noticed that you're issue got a reply that it might be about quoting. Did you already try that one?

**Comment by RedBaron2** [comment]
@johanjanssen 
I updated my local version with a change for the processing of the installdir variable. It installs without complaints. I'll update this PR tomorrow hopefully.

**Comment by RedBaron2** [comment]
@johanjanssen 
Adjustments made and fixed the spacing issue with helper

**Comment by johanjanssen** [comment]
@RedBaron2 thanks a lot for the fixes!

**Pull request merged**
