### PR TITLE
(adoptopenjdk) Update to fix issue with custom install folder

### PR DESCRIPTION
**Pull request by RedBaron2**
@johanjanssen @johanjanssen-sanoma 
This will fix the issue of not being able to customize the `InstallDir`. This was caused by a `-replace` command that was a tad over replacing. This also fixes issue #13 with the empty `FileType` for the `chocolateyinstall.ps1` files.

This should make it work like @rgl would like in issue #12

### CODE REVIEW

**Comment by johanjanssen** [comment]
@RedBaron2 thanks for the quick fixes. I did some checks. The install-dir indeed works now. The FileType is also filled.

However I noticed something strange, it seems the version is not correct. I now see versions that end on 1000 or 3600 instead of 10 or 36. I just ran the old script again to see the difference with the new script:

Old script
    <version>11.0.8.**10**</version>
    <title>AdoptOpenJDK jre11 hotspot 11.0.8.**10**</title>	
New script	
    <version>11.0.8.**1000**</version>
    <title>AdoptOpenJDK jre11 hotspot 11.0.8.**10**</title>

Is that caused by the new Get-FixVersion?

**Comment by RedBaron2** [comment]
Yes, it was done to allow for hot fixes like this one. The extra zeros are for padding should a newer fix version be needed quicker than the normal release schedules. It can easily be turned if you require it.

**Comment by johanjanssen** [comment]
Ah, that really is a feature and not a bug. Good idea!

**Comment by Vankog** [comment]
But could you please clarify this versioning in the title and/or description of the Choco entry?
I was quite confused about it. Searched the net for a 11.0.8.11 and 1.0.8.1000 and was bummed to find only *.10

Maybe you really could find a way to clarify that one version is the JSK version and the other the installer/package version.

Thanks!

**Comment by RedBaron2** [comment]
@Vankog 
I'll work on making the versioning be a bit less exotic and updated to the title in the future.

@johanjanssen 
When should the next update be for these again?

**Comment by johanjanssen** [comment]
@RedBaron2 thanks for picking it up. October 20th OpenJDK releases new minor versions. Normally AdoptOpenJDK needs a few days to create their builds. But don't rush, if you can't make it, we'll add it later. I don't think it's blocking for now, but it's a nice improvement.

What do you plan to change? Maybe just display the 'original' version in the title and add a short description explaining why the version is a bit different than expected?

**Comment by RedBaron2** [comment]
@Vankog 
Title's will be updated to include the new updated versioning

@johanjanssen @Vankog 
The descriptions can be updated to have just under the `AdoptOpenJDK` 
- **_Updated_Version_**
- **_HotFix_Version_**
- **_Quick_Version_**

Please, let me know of what wording would be best.

**Comment by johanjanssen** [comment]
So for a normal release, we would have something like 15.0.1.2000 instead of 15.0.1.2 which we had before.

For a hotfix, we then have something like 15.0.1.2001.

So basically both our normal version numbers and our fixed versions have different numbers than the normal release number. Distinguishing between both scenarios makes it more complicated and error prone. I would simply say in the description what the official version is and then mention that we have slightly different versions to allow fixes for existing versions. Or something like that :).

**Comment by RedBaron2** [comment]
@johanjanssen 
You would have the versioning like normal 11.0.345.2
And the hot fix would be the
11.0.345.2001

Only the 8 versioning would be different
Versioning for hot fix having
8.252.3.20201010 
if today done for today

The description would have the notation 
**Updated_Version**
 right above the regular description if is a hot fix
And nothing if normal version

**Comment by johanjanssen** [comment]
Ok clear, sounds good. I thought that we would always have the last section with extra zero's. Thanks for the explanation.

**Comment by RedBaron2** [comment]
@johanjanssen 
Due to a bug in AU (still working on a possible fix for it)
If a hotfix has been done prior to the current run. The hotfix variable change will not update all packages again.

PR should be submitted next week 🤞

**Pull request merged**
